name: Elektromozaiek
favicon: null
layout_spectrum: 1
typography_spectrum: 0.86805
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefc'
    - '#00020e'
    - '#54676e'
    - '#b0a997'
    - '#71ffff'
  brandStrength: 0.5
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
