name: ΞleқtroӍozѧïeӃ
favicon: null
layout_spectrum: 0.47206
typography_spectrum: 0.86805
title: ΞleқtroӍozѧïeӃ
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000100'
    - '#4e5857'
    - '#dbe4b0'
    - '#ada68a'
    - '#137090'
  brandStrength: 0
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
